In dev, error explicitly with incompatible Node versions
Avoid this opaque error:

TypeError: require.extensions.hasOwnProperty is not a function

See https://github.com/mathisonian/react-editable-svg-label/issues/5